name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish NuGet Maincotech.Common
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/Maincotech.Common/Maincotech.Common.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish NuGet Maincotech.Core
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/Maincotech.Core/Maincotech.Core.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish NuGet Maincotech.Messaging
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/Maincotech.Messaging/Maincotech.Messaging.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
